development:
  adapter: postgresql
  encoding: unicode
  database: bugonrails
  pool: 5
  username: juangarcia

test:
  adapter: postgresql
  encoding: unicode
  database: bugonrails
  pool: 5
  username: juangarcia